version: "3.1"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: testdb
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
